"""initial

Revision ID: 72298cb06ef9
Revises:
Create Date: 2023-11-11 02:18:31.545340

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "72298cb06ef9"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("author", sa.String(length=255), nullable=False),
        sa.Column("genre", sa.String(length=64), nullable=False),
        sa.Column("date_published", postgresql.asyncpg.AsyncpgDate(), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_book")),
        schema="public",
    )
    op.create_index(op.f("ix_book_created_at"), "book", ["created_at"], unique=False, schema="public")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_book_created_at"), table_name="book", schema="public")
    op.drop_table("book", schema="public")
    # ### end Alembic commands ###
