"""denied_lists

Revision ID: 62428fae925b
Revises: 72298cb06ef9
Create Date: 2023-11-12 20:39:54.166667

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "62428fae925b"
down_revision = "72298cb06ef9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book_author_denied_list",
        sa.Column("value", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("value", name=op.f("pk_book_author_denied_list")),
        schema="public",
    )
    op.create_table(
        "book_name_denied_list",
        sa.Column("value", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("value", name=op.f("pk_book_name_denied_list")),
        schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("book_name_denied_list", schema="public")
    op.drop_table("book_author_denied_list", schema="public")
    # ### end Alembic commands ###
